# --- Telegram Bot ---
# (Pon el nombre de usuario de tu bot de @BotFather)
telegram.bot.username=Unsta_bot
# (Esta es la variable de entorno para el token)
telegram.bot.token=${TELEGRAM_BOT_TOKEN}

# --- Gemini AI ---
# (Esta es la variable de entorno para la API Key)
gemini.api.key=${GEMINI_API_KEY}
# (URL de la API v1beta)
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.0-pro:generateContent


# --- Server ---
# (Asegura que la app web se inicie)
server.port=8080