# --- Telegram Bot ---
# (Pon el nombre de usuario de tu bot de @BotFather)
telegram.bot.username=Unsta_bot
# (Esta es la variable de entorno para el token)
telegram.bot.token=${TELEGRAM_BOT_TOKEN}

groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
# --- Server ---
# (Asegura que la app web se inicie)
server.port=8080